# Generated by Django 4.1 on 2022-08-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdcine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='fecha_estreno',
            new_name='agno_estreno',
        ),
    ]
