# Generated by Django 4.1 on 2022-08-10 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdcine', '0002_rename_fecha_estreno_peliculas_agno_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='agno_estreno',
            field=models.PositiveIntegerField(default=1950, validators=[django.core.validators.MinValueValidator(1895)]),
        ),
    ]
